# Generated by Django 3.0.3 on 2020-02-15 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seating_capacity', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(15)])),
                ('web_lecture_support', models.BooleanField(default=False)),
                ('shape', models.PositiveSmallIntegerField(choices=[(1, 'oval'), (2, 'rectangular'), (3, 'canopy'), (4, 'elevated')])),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('contact_number', models.CharField(max_length=10)),
                ('relation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(120)])),
                ('total_duration', models.IntegerField()),
                ('chapters', models.ManyToManyField(to='entity.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('date_of_joining', models.DateField()),
                ('salary', models.FloatField(help_text='In LPA')),
                ('subject', models.ManyToManyField(to='entity.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('date_of_joining', models.DateField()),
                ('standard', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(10)])),
                ('roll_no', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('point_of_contact', models.ManyToManyField(to='entity.Relative')),
            ],
        ),
    ]
