# Generated by Django 3.0.3 on 2020-02-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_auto_20200215_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.ClassRoom')),
                ('students', models.ManyToManyField(to='entity.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Teacher')),
            ],
        ),
    ]
