# Generated by Django 3.0.3 on 2020-02-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='web_lecture',
            field=models.BooleanField(default=False),
        ),
    ]
