# Generated by Django 3.0.3 on 2020-02-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='shape',
            field=models.PositiveSmallIntegerField(choices=[('oval', 'oval'), ('rectangular', 'rectangular'), ('canopy', 'canopy'), ('elevated', 'elevated')]),
        ),
    ]
